### ISSUE TITLE
[SOLVED] Notifications not showing

### ISSUE THREAD

**Issue by User4716** [ChristianGalla/AutoStartConfirm#104]
As of now, this program only seems to monitor if a new autorun entry is added or an old one is deleted, but it doesn't monitor any modifications to already existing autorun entries. 

It would be nice if there was an optional setting that with it turned on, the program would simply notify me that the data of the specific autorun entry has changed.

This module doesn't need to monitor the values of the autorun registry entries (or other autorun methods), it doesn't need to know what it changed to or what it was, it only needs to know that something has changed. (This would greatly enhance the efficiency of this software and save processing power.)

**Comment by ChristianGalla** [comment]
If for example a scheduled tasks exists to run an exe file, should be monitored (1) if the scheduled task has been changed to start at another event / time, or (2) if the content of the exe file has been replaced?

Registry keys and their values are already monitored using only a few resources:
When Auto Start Confirm is started, all locations are checked once for changes since the last run to process changes when the program was not running. After this, Auto Start Confirm subscribes to registry changes. Only if changes occur, Windows calls Auto Start Confirm to process what has changed. 
Also, all monitoring and compare tasks are running in low priority background threads to impact other programs as less as possible.

Are you experiencing performance issues?

**Comment by ChristianGalla** [comment]
Are you using the latest version of Auto Start Confirm?

Do you see "confirmed" in the status column? The green checkmark button at the left can be used to confirm an auto start entry without using the toast notification. After it has been confirmed, the checkmark button is greyed out.

Auto Start Confirm uses the native toast notification feature of windows. Please ensure toast notifications are not globally disabled in Windows or explicitly blocked for the program Auto Start Confirm.
For example focus mode may prevent toast notifications: https://support.microsoft.com/en-us/windows/make-it-easier-to-focus-on-tasks-0d259fd9-e9d0-702c-c027-007f0e78eaf2
